### ISSUE TITLE
Cannot be installed this plugin getting error like below. Do you have any solution

### ISSUE THREAD

**Issue by Asfath** [denkomanceski/windowSoftInputMode#2]
cordova plugin add https://github.com/denkomanceski/windowSoftInputMode.git
(node:9372) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plug                                                                                                                                  in https://github.com/denkomanceski/windowSoftInputMode.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: git+https://git                                                                                                                                  hub.com/denkomanceski/windowSoftInputMode.git.
npm ERR! package.json npm can't find a package.json file in your current directo                                                                                                                                  ry.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-11-13T04_56_49_8                                                                                                                                  51Z-debug.log
    at C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\cordo                                                                                                                                  va-lib\src\plugman\fetch.js:173:37
    at _rejected (C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_mo                                                                                                                                  dules\q\q.js:864:24)
    at C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.j                                                                                                                                  s:890:30
    at Promise.when (C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node                                                                                                                                  _modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\Users\user\AppData\Roaming\npm\node_m                                                                                                                                  odules\cordova\node_modules\q\q.js:808:41)
    at C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.j                                                                                                                                  s:624:44
    at runSingle (C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_mo                                                                                                                                  dules\q\q.js:137:13)
    at flush (C:\Users\user\AppData\Roaming\npm\node_modules\cordova\node_module                                                                                                                                  s\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:9372) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This                                                                                                                                   error originated either by throwing inside of an async function without a catch                                                                                                                                   block, or by rejecting a promise which was not handled with .catch(). (rejection                                                                                                                                   id: 1)
(node:9372) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre                                                                                                                                  cated. In the future, promise rejections that are not handled will terminate the                                                                                                                                   Node.js process with a non-zero exit code.

**Comment by razcakappa** [comment]
Debug log also added below

`0 info it worked if it ends with ok`
`1 verbose cli [ '/usr/local/Cellar/node/10.11.0/bin/node',`
`1 verbose cli   '/usr/local/bin/npm',`
`1 verbose cli   'install',`
`1 verbose cli   'https://github.com/denkomanceski/windowSoftInputMode.git',`
`1 verbose cli   '--production',`
`1 verbose cli   '--save-exact' ]`
`2 info using npm@6.4.1`
`3 info using node@v10.11.0`
`4 verbose npm-session 508b4a451b46bbe9`
`5 silly install loadCurrentTree`
`6 silly install readLocalPackageData`
`7 silly fetchPackageMetaData error for git+https://github.com/denkomanceski/windowSoftInputMode.git premature close`
`8 timing stage:rollbackFailedOptional Completed in 1ms`
`9 timing stage:runTopLevelLifecycles Completed in 7341ms`
`10 verbose stack Error: premature close`
`10 verbose stack     at PassThrough.onclose (/usr/local/lib/node_modules/npm/node_modules/end-of-stream/index.js:47:67)`
`10 verbose stack     at PassThrough.emit (events.js:187:15)`
`10 verbose stack     at emitCloseNT (internal/streams/destroy.js:59:8)`
`10 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)`
`11 verbose cwd /Users/dev/projects/financia-mobile-app`
`12 verbose Darwin 17.7.0`
`13 verbose argv "/usr/local/Cellar/node/10.11.0/bin/node" "/usr/local/bin/npm" "install" "https://github.com/denkomanceski/windowSoftInputMode.git" "--production" "--save-exact"`
`14 verbose node v10.11.0`
`15 verbose npm  v6.4.1`
`16 error premature close`
`17 verbose exit [ 1, true ]`

**Comment by PetersonRyan** [comment]
Late reply, but the plugin is a little old and Cordova now requires a package.json. 
I've updated this in my fork of the repo, and submitted a pull request that hopefully gets approved.

You can use this version here:
https://github.com/PetersonRyan/windowSoftInputMode
